# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Fuze360Banner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fuze360Banner
  pod 'Fuze360SDK', :git => 'https://github.com/fuze360/Fuze360-iOS-SDK.git', :tag => '1.0.0'

end
